# Generated by Django 6.0 on 2025-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
